services:
    oro_layout.block_type.base:
        class: Oro\Component\Layout\Block\Type\BaseType
        tags:
             - { name: layout.block_type, alias: layout }

    oro_layout.block_type.container:
        class: Oro\Component\Layout\Block\Type\ContainerType
        tags:
             - { name: layout.block_type, alias: container }

    oro_layout.block_type.root:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\RootType
        tags:
             - { name: layout.block_type, alias: root }

    oro_layout.block_type.head:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\HeadType
        tags:
             - { name: layout.block_type, alias: head }

    oro_layout.block_type.meta:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\MetaType
        tags:
             - { name: layout.block_type, alias: meta }

    oro_layout.block_type.script:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\ScriptType
        tags:
             - { name: layout.block_type, alias: script }

    oro_layout.block_type.style:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\StyleType
        tags:
             - { name: layout.block_type, alias: style }

    oro_layout.block_type.body:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\BodyType
        tags:
             - { name: layout.block_type, alias: body }
