parameters:
    oro_layout.layout_factory_builder.class:    Oro\Component\Layout\LayoutFactoryBuilder
    oro_layout.layout_manager.class:            Oro\Component\Layout\LayoutManager

services:
    oro_layout.extension:
        public: false
        class: Oro\Component\Layout\Extension\DependencyInjection\DependencyInjectionExtension
        arguments:
            - @service_container
            - {}
            - {}
            - {}

    oro_layout.extension.core:
        public: false
        class: Oro\Component\Layout\Extension\Core\CoreExtension

    oro_layout.layout_factory_builder:
        public: false
        class: %oro_layout.layout_factory_builder.class%
        calls:
            - [addExtension, [@oro_layout.extension.core, -10]]
            - [addExtension, [@oro_layout.extension]]
            - [setDefaultRenderer, [%oro_layout.templating.default%]]

    oro_layout.layout_manager:
        class: %oro_layout.layout_manager.class%
        arguments:
            - @oro_layout.layout_factory_builder
