parameters:
    oro_layout.block_type_factory.class:  Oro\Component\Layout\DependencyInjectionBlockTypeFactory

services:
    oro_layout.block_type_factory:
        class: %oro_layout.block_type_factory.class%
        arguments:
            - @service_container
            - {}

    oro_layout.type.base:
        class: Oro\Component\Layout\Block\Type\BaseType
        tags:
             - { name: layout.type, alias: layout }

    oro_layout.type.container:
        class: Oro\Component\Layout\Block\Type\ContainerType
        tags:
             - { name: layout.type, alias: container }

    oro_layout.type.root:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\RootType
        tags:
             - { name: layout.type, alias: root }

    oro_layout.type.head:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\HeadType
        tags:
             - { name: layout.type, alias: head }

    oro_layout.type.meta:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\MetaType
        tags:
             - { name: layout.type, alias: meta }

    oro_layout.type.script:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\ScriptType
        tags:
             - { name: layout.type, alias: script }

    oro_layout.type.style:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\StyleType
        tags:
             - { name: layout.type, alias: style }

    oro_layout.type.body:
        class: Oro\Bundle\LayoutBundle\Layout\Block\Type\BodyType
        tags:
             - { name: layout.type, alias: body }
