parameters:
    oro_layout.layout_factory_builder.class:    Oro\Component\Layout\LayoutFactoryBuilder
    oro_layout.layout_manager.class:            Oro\Component\Layout\LayoutManager
    oro_layout.form_layout_builder.class:       Oro\Bundle\LayoutBundle\Layout\Form\GroupingFormLayoutBuilder

services:
    oro_layout.extension:
        public: false
        class: Oro\Component\Layout\Extension\DependencyInjection\DependencyInjectionExtension
        arguments:
            - @service_container
            - {}
            - {}
            - {}

    oro_layout.layout_factory_builder:
        public: false
        class: %oro_layout.layout_factory_builder.class%
        calls:
            - [addExtension, [@oro_layout.extension]]
            - [addExtension, [@oro_layout.theme_extension]]
            - [setDefaultRenderer, [%oro_layout.templating.default%]]

    oro_layout.layout_manager:
        class: %oro_layout.layout_manager.class%
        arguments:
            - @oro_layout.layout_factory_builder

    oro_layout.form_layout_builder:
        class: %oro_layout.form_layout_builder.class%
        calls:
            - [addSimpleFormTypes, [['choice', 'datetime', 'date', 'time']]]
