parameters:
    oro_layout.extension.class:                 Oro\Component\Layout\Extension\DependencyInjection\DependencyInjectionExtension
    oro_layout.extension_manager.class:         Oro\Component\Layout\ExtensionManager
    oro_layout.block_factory.class:             Oro\Component\Layout\BlockFactory
    oro_layout.raw_layout_builder.class:        Oro\Component\Layout\RawLayoutBuilder
    oro_layout.layout_manipulator.class:        Oro\Component\Layout\DeferredLayoutManipulator
    oro_layout.layout_factory.class:            Oro\Component\Layout\LayoutFactory
    oro_layout.layout_builder.class:            Oro\Component\Layout\LayoutBuilder
    oro_layout.layout_renderer_registry.class:  Oro\Component\Layout\LayoutRendererRegistry
    oro_layout.layout_manager.class:            Oro\Component\Layout\LayoutManager

services:
    oro_layout.extension:
        public: false
        class: %oro_layout.extension.class%
        arguments:
            - @service_container
            - {}
            - {}
            - {}

    oro_layout.extension_manager:
        public: false
        class: %oro_layout.extension_manager.class%
        calls:
            - [addExtension, [@oro_layout.extension]]

    oro_layout.raw_layout_builder:
        public: false
        class: %oro_layout.raw_layout_builder.class%

    oro_layout.layout_manipulator:
        public: false
        class: %oro_layout.layout_manipulator.class%
        arguments:
            - @oro_layout.raw_layout_builder
            - @oro_layout.extension_manager

    oro_layout.block_factory:
        public: false
        class: %oro_layout.block_factory.class%
        arguments:
            - @oro_layout.extension_manager
            - @oro_layout.layout_manipulator

    oro_layout.layout_factory:
        public: false
        class: %oro_layout.layout_factory.class%
        arguments:
            - @oro_layout.layout_renderer_registry

    oro_layout.layout_builder:
        public: false
        class: %oro_layout.layout_builder.class%
        arguments:
            - @oro_layout.raw_layout_builder
            - @oro_layout.layout_manipulator
            - @oro_layout.block_factory
            - @oro_layout.layout_factory

    oro_layout.layout_renderer_registry:
        public: false
        class: %oro_layout.layout_renderer_registry.class%
        calls:
            - [ setDefaultRenderer, [%oro_layout.templating.default%] ]

    oro_layout.layout_manager:
        class: %oro_layout.layout_manager.class%
        arguments:
            - @oro_layout.layout_builder
