parameters:
    oro_layout.block_type_factory.class:  Oro\Component\Layout\DependencyInjectionBlockTypeFactory;
    oro_layout.block_type.root.class:     Oro\Component\Layout\Block\Type\RootBlockType;
    oro_layout.block_type.head.class:     Oro\Component\Layout\Block\Type\HeadBlockType;
    oro_layout.block_type.script.class:   Oro\Component\Layout\Block\Type\ScriptBlockType;
    oro_layout.block_type.style.class:    Oro\Component\Layout\Block\Type\StyleBlockType;
    oro_layout.block_type.body.class:     Oro\Component\Layout\Block\Type\BodyBlockType;

services:
    oro_layout.block_type_factory:
        class: %oro_layout.block_type_factory.class%
        arguments:
            - @service_container
            - {}

    oro_layout.block_type.root:
        class: %oro_layout.block_type.root.class%

    oro_layout.block_type.head:
        class: %oro_layout.block_type.head.class%

    oro_layout.block_type.script:
        class: %oro_layout.block_type.script.class%

    oro_layout.block_type.style:
        class: %oro_layout.block_type.style.class%

    oro_layout.block_type.body:
        class: %oro_layout.block_type.body.class%
