parameters:
    oro_layout.theme_factory.class:                    Oro\Component\Layout\Extension\Theme\Model\ThemeFactory
    oro_layout.theme_manager.class:                    Oro\Component\Layout\Extension\Theme\Model\ThemeManager
    oro_layout.theme_extension.class:                  Oro\Component\Layout\Extension\Theme\ThemeExtension
    oro_layout.request.listener.theme.class:           Oro\Bundle\LayoutBundle\EventListener\ThemeListener

    oro_layout.loader.default_resource_factory.class:  Oro\Component\Layout\Extension\Theme\Loader\ResourceFactory

    oro_layout.loader.php_file_loader.class:           Oro\Component\Layout\Extension\Theme\Loader\PhpFileLoader
    oro_layout.loader.yaml_file_loader.class:          Oro\Component\Layout\Extension\Theme\Loader\YamlFileLoader

    oro_layout.default_active_theme:    ~
    oro_layout.theme_updates_resources: []
    oro_layout.updates_cache_dir:       %kernel.cache_dir%/layouts

services:
    oro_layout.dependency_initializer:
        class:  Oro\Component\Layout\Extension\Theme\Model\DependencyInitializer
        public: false
        arguments:
            - @service_container
        calls:
            - [addKnownDependency, ['\Oro\Component\ConfigExpression\ExpressionFactoryAwareInterface', 'setExpressionFactory', 'oro_layout.expression.factory']]

    oro_layout.theme_factory:
        class:  %oro_layout.theme_factory.class%
        public: false

    oro_layout.theme_manager:
        class:  %oro_layout.theme_manager.class%
        public: false
        arguments:
            - @oro_layout.theme_factory
            - []

    oro_layout.loader:
        class:  Oro\Component\Layout\Extension\Theme\Loader\ChainLoader
        public: false
        calls:
            - [addLoader, [@oro_layout.loader.yaml_file_loader]]
            - [addLoader, [@oro_layout.loader.php_file_loader]]

    oro_layout.loader.default_resource_factory:
        class:  %oro_layout.loader.default_resource_factory.class%
        public: false

    oro_layout.loader.php_file_loader:
        class:  %oro_layout.loader.php_file_loader.class%
        public: false
        arguments:
            - @oro_layout.php_layout_update_generator
            - %kernel.debug%
            - %oro_layout.updates_cache_dir%

    oro_layout.loader.yaml_file_loader:
        class:  %oro_layout.loader.yaml_file_loader.class%
        public: false
        arguments:
            - @oro_layout.config_layout_update_generator
            - %kernel.debug%
            - %oro_layout.updates_cache_dir%

    oro_layout.loader.path_provider:
        class:  Oro\Component\Layout\Extension\Theme\Loader\ChainPathProvider
        public: false

    oro_layout.loader.theme_path_provider:
        class: Oro\Component\Layout\Extension\Theme\Loader\ThemePathProvider
        public: false
        arguments:
            - @oro_layout.theme_manager
        tags:
            - { name: layout.resource.path_provider }

    oro_layout.layout_context_configurator.theme:
        class: Oro\Bundle\LayoutBundle\Layout\Extension\ThemeContextConfigurator
        calls:
            - [setRequest, [@?request=]]
        tags:
            - { name: layout.context_configurator, priority: -100 }

    oro_layout.theme_extension:
        class: %oro_layout.theme_extension.class%
        arguments:
            - %oro_layout.theme_updates_resources%
            - @oro_layout.loader.default_resource_factory
            - @oro_layout.loader
            - @oro_layout.dependency_initializer
            - @oro_layout.loader.path_provider
        calls:
            - [setLogger, [ @logger ]]

    oro_layout.data_provider.theme:
        class: Oro\Component\Layout\Extension\Theme\DataProvider\ThemeDataProvider
        arguments:
            - @oro_layout.theme_manager
        tags:
            - { name: layout.data_provider, alias: theme }

    oro_layout.yaml_updates_warmer:
        class: Oro\Bundle\LayoutBundle\CacheWarmer\LayoutUpdatesWarmer
        public: false
        arguments:
            - %oro_layout.theme_updates_resources%
            - @oro_layout.loader.default_resource_factory
            - @oro_layout.loader
        tags:
            - { name: kernel.cache_warmer }

    oro_layout.config_layout_update_generator:
        class:  Oro\Component\Layout\Extension\Theme\Generator\ConfigLayoutUpdateGenerator
        public: false
        arguments:
            - @oro_layout.expression.assembler

    oro_layout.php_layout_update_generator:
        class:  Oro\Component\Layout\Extension\Theme\Generator\PhpLayoutUpdateGenerator
        public: false

    oro_layout.request.listener.theme:
        class: %oro_layout.request.listener.theme.class%
        arguments:
            - %oro_layout.default_active_theme%
        tags:
            - { name: kernel.event_subscriber }
