parameters:
    oro_layout.twig.extension.layout.class:   Oro\Bundle\LayoutBundle\Twig\LayoutExtension
    oro_layout.twig.renderer.class:           Symfony\Bridge\Twig\Form\TwigRenderer
    oro_layout.twig.renderer.engine.class:    Symfony\Bridge\Twig\Form\TwigRendererEngine
    oro_layout.twig.block_renderer.class:     Oro\Bundle\LayoutBundle\Layout\TwigBlockRenderer

services:
    oro_layout.twig.extension.array:
        public: false
        class: Oro\Bundle\LayoutBundle\Twig\ArrayExtension
        tags:
            - { name: twig.extension }

    oro_layout.twig.extension.layout:
        public: false
        class: %oro_layout.twig.extension.layout.class%
        arguments:
            - @oro_layout.twig.renderer
        tags:
            - { name: twig.extension }

    oro_layout.twig.renderer:
        public: false
        class: %oro_layout.twig.renderer.class%
        arguments:
            - @oro_layout.twig.renderer.engine

    oro_layout.twig.renderer.engine:
        public: false
        class: %oro_layout.twig.renderer.engine.class%
        arguments:
            - %oro_layout.twig.resources%

    oro_layout.twig.block_renderer:
        public: false
        class: %oro_layout.twig.block_renderer.class%
        arguments:
            - @oro_layout.twig.renderer
            - @twig
